namespace GUI
{
    partial class frmGestorPrendas
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.pnlHeader      = new System.Windows.Forms.Panel();
            this.lblTitulo      = new System.Windows.Forms.Label();
            this.pnlContent     = new System.Windows.Forms.Panel();
            this.dgvPrendas     = new System.Windows.Forms.DataGridView();
            this.pnlCampos      = new System.Windows.Forms.Panel();
            this.lblCamposTitle = new System.Windows.Forms.Label();
            this.lblNombre      = new System.Windows.Forms.Label();
            this.txtNombre      = new System.Windows.Forms.TextBox();
            this.lblColor       = new System.Windows.Forms.Label();
            this.txtColor       = new System.Windows.Forms.TextBox();
            this.lblTalla       = new System.Windows.Forms.Label();
            this.txtTalla       = new System.Windows.Forms.TextBox();
            this.lblTemporada   = new System.Windows.Forms.Label();
            this.cboTemporada   = new System.Windows.Forms.ComboBox();
            this.lblCategoria   = new System.Windows.Forms.Label();
            this.cboCategorias  = new System.Windows.Forms.ComboBox();
            this.lblDescripcion = new System.Windows.Forms.Label();
            this.btnNuevo       = new System.Windows.Forms.Button();
            this.btnGuardar     = new System.Windows.Forms.Button();
            this.btnEliminar    = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPrendas)).BeginInit();
            this.pnlContent.SuspendLayout();
            this.pnlHeader.SuspendLayout();
            this.pnlCampos.SuspendLayout();
            this.SuspendLayout();
            // pnlHeader
            this.pnlHeader.BackColor = System.Drawing.Color.FromArgb(180, 35, 75);
            this.pnlHeader.Dock      = System.Windows.Forms.DockStyle.Top;
            this.pnlHeader.Height    = 58;
            this.pnlHeader.Name      = "pnlHeader";
            this.pnlHeader.Controls.Add(this.lblTitulo);
            this.lblTitulo.AutoSize  = true;
            this.lblTitulo.Font      = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblTitulo.ForeColor = System.Drawing.Color.White;
            this.lblTitulo.Location  = new System.Drawing.Point(18, 18);
            this.lblTitulo.Name      = "lblTitulo";
            this.lblTitulo.Text      = "Gestor de Prendas";
            // pnlContent
            this.pnlContent.BackColor = System.Drawing.Color.FromArgb(255, 240, 248);
            this.pnlContent.Dock      = System.Windows.Forms.DockStyle.Fill;
            this.pnlContent.Name      = "pnlContent";
            this.pnlContent.Padding   = new System.Windows.Forms.Padding(14);
            this.pnlContent.Controls.Add(this.dgvPrendas);
            this.pnlContent.Controls.Add(this.pnlCampos);
            this.pnlContent.Controls.Add(this.lblDescripcion);
            // dgvPrendas
            this.dgvPrendas.AllowUserToAddRows    = false;
            this.dgvPrendas.AllowUserToDeleteRows = false;
            this.dgvPrendas.MultiSelect           = false;
            this.dgvPrendas.ReadOnly              = true;
            this.dgvPrendas.SelectionMode         = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvPrendas.Location              = new System.Drawing.Point(14, 14);
            this.dgvPrendas.Name                  = "dgvPrendas";
            this.dgvPrendas.Size                  = new System.Drawing.Size(540, 380);
            this.dgvPrendas.TabIndex              = 0;
            this.dgvPrendas.BackgroundColor                     = System.Drawing.Color.White;
            this.dgvPrendas.BorderStyle                         = System.Windows.Forms.BorderStyle.None;
            this.dgvPrendas.CellBorderStyle                     = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvPrendas.GridColor                           = System.Drawing.Color.FromArgb(220, 170, 195);
            this.dgvPrendas.EnableHeadersVisualStyles           = false;
            this.dgvPrendas.ColumnHeadersBorderStyle            = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.dgvPrendas.ColumnHeadersDefaultCellStyle.BackColor  = System.Drawing.Color.FromArgb(180, 35, 75);
            this.dgvPrendas.ColumnHeadersDefaultCellStyle.ForeColor  = System.Drawing.Color.White;
            this.dgvPrendas.ColumnHeadersDefaultCellStyle.Font       = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.dgvPrendas.ColumnHeadersDefaultCellStyle.Padding    = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.dgvPrendas.ColumnHeadersHeight                 = 36;
            this.dgvPrendas.DefaultCellStyle.BackColor          = System.Drawing.Color.White;
            this.dgvPrendas.DefaultCellStyle.ForeColor          = System.Drawing.Color.FromArgb(35, 20, 30);
            this.dgvPrendas.DefaultCellStyle.Font               = new System.Drawing.Font("Segoe UI", 9.5F);
            this.dgvPrendas.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(232, 120, 160);
            this.dgvPrendas.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgvPrendas.DefaultCellStyle.Padding            = new System.Windows.Forms.Padding(4, 0, 0, 0);
            this.dgvPrendas.AlternatingRowsDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(255, 225, 238);
            this.dgvPrendas.RowHeadersVisible                   = false;
            this.dgvPrendas.RowTemplate.Height                  = 28;
            this.dgvPrendas.SelectionChanged += new System.EventHandler(this.dgvPrendas_SelectionChanged);
            // lblDescripcion (resultado Decorator - abajo del grid)
            this.lblDescripcion.AutoSize  = false;
            this.lblDescripcion.Font      = new System.Drawing.Font("Segoe UI", 9.5F);
            this.lblDescripcion.ForeColor = System.Drawing.Color.FromArgb(180, 35, 75);
            this.lblDescripcion.Location  = new System.Drawing.Point(14, 404);
            this.lblDescripcion.Name      = "lblDescripcion";
            this.lblDescripcion.Size      = new System.Drawing.Size(540, 50);
            this.lblDescripcion.Text      = "";
            // pnlCampos
            this.pnlCampos.BackColor = System.Drawing.Color.White;
            this.pnlCampos.Location  = new System.Drawing.Point(570, 14);
            this.pnlCampos.Name      = "pnlCampos";
            this.pnlCampos.Size      = new System.Drawing.Size(230, 450);
            this.pnlCampos.Controls.Add(this.lblCamposTitle);
            this.pnlCampos.Controls.Add(this.lblNombre);
            this.pnlCampos.Controls.Add(this.txtNombre);
            this.pnlCampos.Controls.Add(this.lblColor);
            this.pnlCampos.Controls.Add(this.txtColor);
            this.pnlCampos.Controls.Add(this.lblTalla);
            this.pnlCampos.Controls.Add(this.txtTalla);
            this.pnlCampos.Controls.Add(this.lblTemporada);
            this.pnlCampos.Controls.Add(this.cboTemporada);
            this.pnlCampos.Controls.Add(this.lblCategoria);
            this.pnlCampos.Controls.Add(this.cboCategorias);
            this.pnlCampos.Controls.Add(this.btnNuevo);
            this.pnlCampos.Controls.Add(this.btnGuardar);
            this.pnlCampos.Controls.Add(this.btnEliminar);
            // lblCamposTitle
            this.lblCamposTitle.AutoSize  = true;
            this.lblCamposTitle.Font      = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.lblCamposTitle.ForeColor = System.Drawing.Color.FromArgb(180, 35, 75);
            this.lblCamposTitle.Location  = new System.Drawing.Point(15, 16);
            this.lblCamposTitle.Name      = "lblCamposTitle";
            this.lblCamposTitle.Text      = "Datos de Prenda";
            // lblNombre
            this.lblNombre.AutoSize  = true;
            this.lblNombre.Font      = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblNombre.ForeColor = System.Drawing.Color.FromArgb(150, 80, 105);
            this.lblNombre.Location  = new System.Drawing.Point(15, 50);
            this.lblNombre.Name      = "lblNombre";
            this.lblNombre.Text      = "NOMBRE";
            this.txtNombre.BackColor    = System.Drawing.Color.FromArgb(255, 240, 248);
            this.txtNombre.BorderStyle  = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtNombre.Font         = new System.Drawing.Font("Segoe UI", 9.5F);
            this.txtNombre.ForeColor    = System.Drawing.Color.FromArgb(35, 20, 30);
            this.txtNombre.Location     = new System.Drawing.Point(15, 70);
            this.txtNombre.Name         = "txtNombre";
            this.txtNombre.Size         = new System.Drawing.Size(200, 30);
            this.txtNombre.TabIndex     = 1;
            // lblColor
            this.lblColor.AutoSize  = true;
            this.lblColor.Font      = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblColor.ForeColor = System.Drawing.Color.FromArgb(150, 80, 105);
            this.lblColor.Location  = new System.Drawing.Point(15, 112);
            this.lblColor.Name      = "lblColor";
            this.lblColor.Text      = "COLOR";
            this.txtColor.BackColor    = System.Drawing.Color.FromArgb(255, 240, 248);
            this.txtColor.BorderStyle  = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtColor.Font         = new System.Drawing.Font("Segoe UI", 9.5F);
            this.txtColor.ForeColor    = System.Drawing.Color.FromArgb(35, 20, 30);
            this.txtColor.Location     = new System.Drawing.Point(15, 132);
            this.txtColor.Name         = "txtColor";
            this.txtColor.Size         = new System.Drawing.Size(200, 30);
            this.txtColor.TabIndex     = 2;
            // lblTalla
            this.lblTalla.AutoSize  = true;
            this.lblTalla.Font      = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblTalla.ForeColor = System.Drawing.Color.FromArgb(150, 80, 105);
            this.lblTalla.Location  = new System.Drawing.Point(15, 174);
            this.lblTalla.Name      = "lblTalla";
            this.lblTalla.Text      = "TALLA";
            this.txtTalla.BackColor    = System.Drawing.Color.FromArgb(255, 240, 248);
            this.txtTalla.BorderStyle  = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtTalla.Font         = new System.Drawing.Font("Segoe UI", 9.5F);
            this.txtTalla.ForeColor    = System.Drawing.Color.FromArgb(35, 20, 30);
            this.txtTalla.Location     = new System.Drawing.Point(15, 194);
            this.txtTalla.Name         = "txtTalla";
            this.txtTalla.Size         = new System.Drawing.Size(100, 30);
            this.txtTalla.TabIndex     = 3;
            // lblTemporada
            this.lblTemporada.AutoSize  = true;
            this.lblTemporada.Font      = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblTemporada.ForeColor = System.Drawing.Color.FromArgb(150, 80, 105);
            this.lblTemporada.Location  = new System.Drawing.Point(15, 236);
            this.lblTemporada.Name      = "lblTemporada";
            this.lblTemporada.Text      = "TEMPORADA";
            this.cboTemporada.BackColor    = System.Drawing.Color.FromArgb(255, 240, 248);
            this.cboTemporada.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboTemporada.FlatStyle    = System.Windows.Forms.FlatStyle.Flat;
            this.cboTemporada.Font         = new System.Drawing.Font("Segoe UI", 9.5F);
            this.cboTemporada.ForeColor    = System.Drawing.Color.FromArgb(35, 20, 30);
            this.cboTemporada.Location     = new System.Drawing.Point(15, 256);
            this.cboTemporada.Name         = "cboTemporada";
            this.cboTemporada.Size         = new System.Drawing.Size(200, 28);
            this.cboTemporada.TabIndex     = 4;
            // lblCategoria
            this.lblCategoria.AutoSize  = true;
            this.lblCategoria.Font      = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Bold);
            this.lblCategoria.ForeColor = System.Drawing.Color.FromArgb(150, 80, 105);
            this.lblCategoria.Location  = new System.Drawing.Point(15, 296);
            this.lblCategoria.Name      = "lblCategoria";
            this.lblCategoria.Text      = "CATEGORIA";
            this.cboCategorias.BackColor    = System.Drawing.Color.FromArgb(255, 240, 248);
            this.cboCategorias.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboCategorias.FlatStyle    = System.Windows.Forms.FlatStyle.Flat;
            this.cboCategorias.Font         = new System.Drawing.Font("Segoe UI", 9.5F);
            this.cboCategorias.ForeColor    = System.Drawing.Color.FromArgb(35, 20, 30);
            this.cboCategorias.FormattingEnabled = true;
            this.cboCategorias.Location     = new System.Drawing.Point(15, 316);
            this.cboCategorias.Name         = "cboCategorias";
            this.cboCategorias.Size         = new System.Drawing.Size(200, 28);
            this.cboCategorias.TabIndex     = 5;
            // btnNuevo
            this.btnNuevo.BackColor    = System.Drawing.Color.White;
            this.btnNuevo.ForeColor    = System.Drawing.Color.FromArgb(180, 35, 75);
            this.btnNuevo.FlatStyle    = System.Windows.Forms.FlatStyle.Flat;
            this.btnNuevo.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(180, 35, 75);
            this.btnNuevo.FlatAppearance.BorderSize  = 1;
            this.btnNuevo.Font         = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Bold);
            this.btnNuevo.Location     = new System.Drawing.Point(15, 358);
            this.btnNuevo.Name         = "btnNuevo";
            this.btnNuevo.Size         = new System.Drawing.Size(200, 34);
            this.btnNuevo.TabIndex     = 6;
            this.btnNuevo.Text         = "Nuevo";
            this.btnNuevo.Cursor       = System.Windows.Forms.Cursors.Hand;
            this.btnNuevo.Click       += new System.EventHandler(this.btnNuevo_Click);
            this.btnGuardar.BackColor    = System.Drawing.Color.FromArgb(180, 35, 75);
            this.btnGuardar.ForeColor    = System.Drawing.Color.White;
            this.btnGuardar.FlatStyle    = System.Windows.Forms.FlatStyle.Flat;
            this.btnGuardar.FlatAppearance.BorderSize = 0;
            this.btnGuardar.Font         = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Bold);
            this.btnGuardar.Location     = new System.Drawing.Point(15, 402);
            this.btnGuardar.Name         = "btnGuardar";
            this.btnGuardar.Size         = new System.Drawing.Size(200, 34);
            this.btnGuardar.TabIndex     = 7;
            this.btnGuardar.Text         = "Guardar";
            this.btnGuardar.Cursor       = System.Windows.Forms.Cursors.Hand;
            this.btnGuardar.Click       += new System.EventHandler(this.btnGuardar_Click);
            this.btnEliminar.BackColor    = System.Drawing.Color.FromArgb(90, 70, 80);
            this.btnEliminar.ForeColor    = System.Drawing.Color.White;
            this.btnEliminar.FlatStyle    = System.Windows.Forms.FlatStyle.Flat;
            this.btnEliminar.FlatAppearance.BorderSize = 0;
            this.btnEliminar.Font         = new System.Drawing.Font("Segoe UI", 9.5F, System.Drawing.FontStyle.Bold);
            this.btnEliminar.Location     = new System.Drawing.Point(15, 446);
            this.btnEliminar.Name         = "btnEliminar";
            this.btnEliminar.Size         = new System.Drawing.Size(200, 34);
            this.btnEliminar.TabIndex     = 8;
            this.btnEliminar.Text         = "Eliminar";
            this.btnEliminar.Cursor       = System.Windows.Forms.Cursors.Hand;
            this.btnEliminar.Click       += new System.EventHandler(this.btnEliminar_Click);
            // frmGestorPrendas
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode       = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor           = System.Drawing.Color.FromArgb(255, 240, 248);
            this.ClientSize          = new System.Drawing.Size(818, 536);
            this.Controls.Add(this.pnlContent);
            this.Controls.Add(this.pnlHeader);
            this.Font                = new System.Drawing.Font("Segoe UI", 9.5F);
            this.Name                = "frmGestorPrendas";
            this.Text                = "WardrobeFlow - Prendas";
            ((System.ComponentModel.ISupportInitialize)(this.dgvPrendas)).EndInit();
            this.pnlContent.ResumeLayout(false);
            this.pnlContent.PerformLayout();
            this.pnlHeader.ResumeLayout(false);
            this.pnlHeader.PerformLayout();
            this.pnlCampos.ResumeLayout(false);
            this.pnlCampos.PerformLayout();
            this.ResumeLayout(false);
        }

        private System.Windows.Forms.Panel       pnlHeader;
        private System.Windows.Forms.Panel       pnlContent;
        private System.Windows.Forms.Panel       pnlCampos;
        private System.Windows.Forms.Label       lblTitulo;
        private System.Windows.Forms.Label       lblCamposTitle;
        private System.Windows.Forms.DataGridView dgvPrendas;
        private System.Windows.Forms.Label       lblNombre;
        private System.Windows.Forms.TextBox     txtNombre;
        private System.Windows.Forms.Label       lblColor;
        private System.Windows.Forms.TextBox     txtColor;
        private System.Windows.Forms.Label       lblTalla;
        private System.Windows.Forms.TextBox     txtTalla;
        private System.Windows.Forms.Label       lblTemporada;
        private System.Windows.Forms.ComboBox    cboTemporada;
        private System.Windows.Forms.Label       lblCategoria;
        private System.Windows.Forms.ComboBox    cboCategorias;
        private System.Windows.Forms.Label       lblDescripcion;
        private System.Windows.Forms.Button      btnNuevo;
        private System.Windows.Forms.Button      btnGuardar;
        private System.Windows.Forms.Button      btnEliminar;
    }
}
